/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vchro;

import java.awt.ScrollPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import jess.Deffacts;
import jess.Fact;
import jess.JessException;
import jess.Value;

/**
 *
 * @author mamun028
 */
public class MainGUI extends javax.swing.JFrame implements ReteControllerEventListener{
    String clipFile;
    ReteController clipController;
    ArrayList<String> questionList;
    Iterator<String> questionIterator;
    String result;
    String explanation;
    SupervisorFeedback formFeedback;
    /**
     * Creates new form MainGUI
     */
    public MainGUI() throws FileNotFoundException, IOException {
        initComponents();
        clipFile = "vchro/interview.clp";
        //if idealEmployeeConcept.clp dont exist create the file with these default values
        //(assert (idealEmployee (trust 4.0) (neuro 3.5) (consci 3.0) (extro 2.5) (agree 2.0) (coach 4.0)))
        String data = "(assert (idealEmployee (trust 4.0) (neuro 3.5) (consci 3.0) (extro 2.5) (agree 2.0) (coach 4.0)))";
    	File file =new File("idealEmployeeConcept.clp");
        //if file doesnt exists, then create it
        if(!file.exists()){
                file.createNewFile();
        }
        FileWriter fileWritter = new FileWriter(file.getName(),false);
        BufferedWriter bufferWritter = new BufferedWriter(fileWritter);
        bufferWritter.write(data);
        bufferWritter.close();
        
        clipController = new ReteController();
        clipController.addListener(this);
        clipController.loadClipFile(clipFile);
        questionList = new ArrayList<String>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpRadio = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtCandidateName = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuestion = new javax.swing.JTextArea();
        jProgressBar1 = new javax.swing.JProgressBar();
        btnSubmit = new javax.swing.JButton();
        panelAnswerArea = new javax.swing.JPanel();
        lblResult = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        cmbInterviewType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Welcome to the office of Chief Human Resource Officer");

        txtCandidateName.setText("Enter Name, interview then Start");
        txtCandidateName.setName("txtCandidateName"); // NOI18N
        txtCandidateName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCandidateNameActionPerformed(evt);
            }
        });
        txtCandidateName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCandidateNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCandidateNameFocusLost(evt);
            }
        });
        txtCandidateName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCandidateNameKeyTyped(evt);
            }
        });

        btnStart.setText("Start");
        btnStart.setEnabled(false);
        btnStart.setName("btnStart"); // NOI18N
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartMouseClicked(evt);
            }
        });

        txtQuestion.setColumns(20);
        txtQuestion.setRows(5);
        txtQuestion.setText("Question Area");
        txtQuestion.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txtQuestion.setEnabled(false);
        txtQuestion.setMinimumSize(new java.awt.Dimension(240, 80));
        txtQuestion.setName("txtQuestion"); // NOI18N
        jScrollPane1.setViewportView(txtQuestion);

        btnSubmit.setText("Submit");
        btnSubmit.setEnabled(false);
        btnSubmit.setName("btnSubmit"); // NOI18N
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });

        lblResult.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        lblResult.setForeground(new java.awt.Color(255, 51, 0));
        lblResult.setText("Answer Area");
        lblResult.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelAnswerAreaLayout = new javax.swing.GroupLayout(panelAnswerArea);
        panelAnswerArea.setLayout(panelAnswerAreaLayout);
        panelAnswerAreaLayout.setHorizontalGroup(
            panelAnswerAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAnswerAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAnswerAreaLayout.setVerticalGroup(
            panelAnswerAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnswerAreaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblResult)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        btnCancel.setText("Reset");
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });

        cmbInterviewType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Technical Job", "Sales Job", "Marketing Job", "Feedback" }));
        cmbInterviewType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbInterviewTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbInterviewType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCandidateName, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 73, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCancel)
                                .addGap(18, 18, 18)
                                .addComponent(btnSubmit))
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(panelAnswerArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnStart)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel1))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(cmbInterviewType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCandidateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAnswerArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus))
        );

        lblStatus.getAccessibleContext().setAccessibleName("lblStatus");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseClicked
        if(btnStart.isEnabled() && cmbInterviewType.getSelectedIndex() > 0 /*is slected sth valid*/){
            try {
                switch (cmbInterviewType.getSelectedIndex()) {
                    case 1/*Technical Job Starts with CTO interview*/:
                        questionList.addAll(getCTOInterviewQus());
                        break;
                    case 2:
                        questionList.addAll(getCEOInterviewQus());
                        break;
                    case 3/*Other Job Only require CEO Interview*/:
                        questionList.addAll(getCEOInterviewQus());
                        break;
                    case 4:
                    {
                        try {
                            formFeedback = new SupervisorFeedback(txtCandidateName.getText(), this);
                            formFeedback.setVisible(true);
                            this.setEnabled(false);
                            return;
                        } catch (Exception ex) {
                            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    default:
                        break;
                }
                questionIterator = questionList.iterator();
                if(questionIterator.hasNext()){
                    String[] question = questionIterator.next().split("#");
                    if(question.length != 2){
                        JOptionPane.showMessageDialog(this, "CTO Question Parsing Error!! (Don't use #)");
                        return;
                    }
                    ArrayList answerList = new ArrayList();
                    int answerLen = clipController.getRatingScaleMax(question[0])-clipController.getRatingScaleMin(question[0])+1;
                    for(int i=0;i < answerLen;i+=clipController.getRatingScaleStep(question[0])){
                        String radValue = Integer.toString(clipController.getRatingScaleMin(question[0])+i);
                        answerList.add(new JRadioButton(radValue));
                    }
                    txtQuestion.setText(question[1]);
                    radioButtonPanelRedraw(answerList);
                    btnStart.setEnabled(false);
                    btnSubmit.setText(questionIterator.hasNext() ? "Next" : "Finish");
                    btnSubmit.setEnabled(false);
                    btnCancel.setEnabled(true);
                    String interViewType = clipController.getCurrentInterviewMode() == 1 ? "CTO" : "CEO";
                    lblStatus.setText(interViewType + " Interview in progress... Testing ["+question[0]+"]");
                }else{
                    JOptionPane.showMessageDialog(this, "Program can't continue!! No question to ask");
                    btnStart.setEnabled(true);
                    btnSubmit.setText("Next");
                }
                
                jProgressBar1.setIndeterminate(true);
                
            } catch (JessException ex) {
                Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "CTO Question Parsing Error!!");
            }
        }
        
    }//GEN-LAST:event_btnStartMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        if(btnCancel.isEnabled()){
            if(JOptionPane.showConfirmDialog(this, "All data will lost, do you want to reset?") == 0){
                clipController = new ReteController();
                clipController.addListener(this);
                clipController.loadClipFile(clipFile);

                lblStatus.setText("Interview Abandoned!");
                jProgressBar1.setValue(jProgressBar1.getMinimum());
                jProgressBar1.setIndeterminate(false);
                btnSubmit.setEnabled(false);
                cmbInterviewType.setSelectedIndex(0);
                txtCandidateName.setText("");
                result = "Interview Reset";
                txtQuestion.setText("");
                ArrayList<Object> facts = clipController.GetAllFacts();
                for(int i= 0 ;i< facts.size();i++){
                    System.out.println(facts.get(i).toString());
                }
                showResult();
            }
        }
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        if(!((JButton)evt.getSource()).isEnabled())return;
        
        String testQuesIdent = lblStatus.getText();
        testQuesIdent = testQuesIdent.substring(testQuesIdent.indexOf("[") + 1);
        testQuesIdent = testQuesIdent.substring(0, testQuesIdent.indexOf("]"));
        String selectedValue = getSelectedRadBtn();
        if(selectedValue == null || testQuesIdent == null || testQuesIdent.isEmpty()){
            JOptionPane.showMessageDialog(this, "Something wrong with selected value/test question - found null!");
            return;
        }
        String assertAnswer = "(assert (answer (ident "+testQuesIdent+") (text "+selectedValue+")))";
        try {
            System.out.println("Interview Mode # "+clipController.getCurrentInterviewMode());
            boolean isDisq = clipController.isDisqualified(assertAnswer);
            if(isDisq){
                btnSubmit.setText("Finish");
            }else if(!isDisq && clipController.getCurrentInterviewMode() == ReteController.INT_MODE_CTO 
                    && clipController.isEligbileForCEOInterview()){ //check eligible for ceo interview
                questionList.clear();
                questionList.addAll(getCEOInterviewQus());
                questionIterator = questionList.iterator();
                btnSubmit.setText("Next");
            }
        } catch (JessException ex) {
                Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(((JButton)evt.getSource()).getText().equalsIgnoreCase("Next")){
            
            //submit this answer & decide what to do
            
            //prepare next question
            if(questionIterator.hasNext()){
                String[] question = questionIterator.next().split("#");
                if(question.length != 2){
                    JOptionPane.showMessageDialog(this, "CTO Question Parsing Error!! (Don't use #)");
                    return;
                }
                ArrayList answerList = new ArrayList();
                int answerLen = clipController.getRatingScaleMax(question[0])-clipController.getRatingScaleMin(question[0])+1;
                for(int i=0;i < answerLen;i+=clipController.getRatingScaleStep(question[0])){
                    String radValue = Integer.toString(clipController.getRatingScaleMin(question[0])+i);
                    answerList.add(new JRadioButton(radValue));
                }
                txtQuestion.setText(question[1]);
                radioButtonPanelRedraw(answerList);
                btnStart.setEnabled(false);
                btnSubmit.setEnabled(false);
                btnCancel.setEnabled(true);
                btnSubmit.setText(questionIterator.hasNext() ? "Next" : "Finish");
                String interViewType = clipController.getCurrentInterviewMode() == 1 ? "CTO" : "CEO";
                lblStatus.setText(interViewType + " Interview in progress... Testing ["+question[0]+"]");
            }else{
                JOptionPane.showMessageDialog(this, "Program can't continue!! No question to ask");
                btnStart.setEnabled(true);
                btnSubmit.setText("ERROR");
                return;
            }
                
            
        }else if(((JButton)evt.getSource()).getText().equalsIgnoreCase("Finish")){
            lblStatus.setText("Interview Complete!");
            jProgressBar1.setValue(jProgressBar1.getMaximum());
            jProgressBar1.setIndeterminate(false);
            btnSubmit.setEnabled(false);
            result = clipController.GetResult();
            ArrayList<Object> facts = clipController.GetAllFacts();
            for(int i= 0 ;i< facts.size();i++){
                System.out.println(facts.get(i).toString());
            }
            if(result == null || result.equals("")){
                result = "No Result - Check log!";
            }
            showResult();
        }
        
    }//GEN-LAST:event_btnSubmitMouseClicked

    private void cmbInterviewTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbInterviewTypeActionPerformed
        // TODO add your handling code here:
        boolean enabled = cmbInterviewType.getSelectedIndex() > 0 && txtCandidateName.getText().length() > 0 && !txtCandidateName.getText().trim().equals("Enter Name, interview then Start");
        btnStart.setEnabled(enabled);
    }//GEN-LAST:event_cmbInterviewTypeActionPerformed

    private void txtCandidateNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCandidateNameFocusGained
        if(txtCandidateName.getText().trim().equals("Enter Name, interview then Start"))
           txtCandidateName.setText("");
    }//GEN-LAST:event_txtCandidateNameFocusGained

    private void txtCandidateNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCandidateNameFocusLost
        if(txtCandidateName.getText().trim().equals(""))
           txtCandidateName.setText("Enter Name, interview then Start");
    }//GEN-LAST:event_txtCandidateNameFocusLost

    private void txtCandidateNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCandidateNameActionPerformed
        boolean enabled = cmbInterviewType.getSelectedIndex() > 0 && txtCandidateName.getText().length() > 0 && !txtCandidateName.getText().trim().equals("Enter Name, interview then Start");
        btnStart.setEnabled(enabled);
    }//GEN-LAST:event_txtCandidateNameActionPerformed

    private void txtCandidateNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCandidateNameKeyTyped
        boolean enabled = cmbInterviewType.getSelectedIndex() > 0 && txtCandidateName.getText().length() > 0 && !txtCandidateName.getText().trim().equals("Enter Name, interview then Start");
        btnStart.setEnabled(enabled);
    }//GEN-LAST:event_txtCandidateNameKeyTyped
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainGUI program;
                try {
                    program = new MainGUI();
                    program.pack();
                program.setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.ButtonGroup btnGrpRadio;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbInterviewType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel panelAnswerArea;
    private javax.swing.JTextField txtCandidateName;
    private javax.swing.JTextArea txtQuestion;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clipFileLoaded() {
        Logger.getLogger(MainGUI.class.getName()).log(Level.INFO, "clipFileLoaded");
        lblStatus.setText("Agent File Loaded, pleaset start");
    }

    @Override
    public void clipFileError(String msg) {
        Logger.getLogger(MainGUI.class.getName()).log(Level.INFO, "Clip File Error - {0}", msg);
        lblStatus.setText("Error in agent file loading!!");
        JOptionPane.showMessageDialog(this, msg);
        System.exit(1);
    }
    
    public ArrayList<String> getCTOInterviewQus() throws JessException{
        if(clipController==null)return null;
        Deffacts ctoQuestions = clipController.engine.findDeffacts("technocalquestion");
        ArrayList<String> list = new ArrayList<String>();
        for(int i=0;i < ctoQuestions.getNFacts();i++){
            Fact f = ctoQuestions.getFact(i);
            Value v = f.getSlotValue("text");
            Value vIdent = f.getSlotValue("ident");
            list.add(vIdent.stringValue(clipController.engine.getGlobalContext())+"#"+v.stringValue(clipController.engine.getGlobalContext()));
        }
        clipController.setCurrentInterviewMode(ReteController.INT_MODE_CTO);
        return list;
    }
    
    public ArrayList<String> getCEOInterviewQus() throws JessException{
        if(clipController==null)return null;
        Deffacts ctoQuestions = clipController.engine.findDeffacts("personality-question");
        ArrayList<String> list = new ArrayList<String>();
        for(int i=0;i < ctoQuestions.getNFacts();i++){
            Fact f = ctoQuestions.getFact(i);
            Value v = f.getSlotValue("text");
            Value vIdent = f.getSlotValue("ident");
            list.add(vIdent.stringValue(clipController.engine.getGlobalContext())+"#"+v.stringValue(clipController.engine.getGlobalContext()));
        }
        clipController.setCurrentInterviewMode(ReteController.INT_MODE_CEO);
        return list;
    }
    
    //add result panel items
    private void radioButtonPanelRedraw(ArrayList radBtns){
       //reset the button group
       panelAnswerArea.removeAll();
       btnGrpRadio.clearSelection();
       for (Enumeration<AbstractButton> btns = btnGrpRadio.getElements(); btns.hasMoreElements();) {
            btnGrpRadio.remove(btns.nextElement());
       }
       
       JPanel panelRadio = new JPanel();
       
       //add action listener
       for(int i=0; i<radBtns.size(); i++){
           JRadioButton radBtn = (JRadioButton)radBtns.get(i);
           radBtn.setSelected(false);
           radBtn.addActionListener(new ActionListener(){
               @Override
               public void actionPerformed(ActionEvent event) {
                   //JRadioButton radSelected = (JRadioButton) event.getSource();
                   btnSubmit.setEnabled(true);
               }
               
           });
           btnGrpRadio.add(radBtn);
           panelRadio.add(radBtn);
       }
       // create scroll pane
       ScrollPane scrollPane = new ScrollPane();
       scrollPane.add(panelRadio);
       scrollPane.setSize(440,100);
        
       //scrollPane.addActionListener(actionListener);
        
       // combine the panels
       panelAnswerArea.add(scrollPane);
       panelAnswerArea.revalidate();
   }
   
   private synchronized String getSelectedRadBtn(){
       //System.out.println("No of btn in btngrp: "+btnGrpRadio.getButtonCount());
       String selectedVal = null;
       for (Enumeration<AbstractButton> buttons = btnGrpRadio.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                selectedVal = button.getText();
                //reset the button group
                break;
            }
        }
        btnGrpRadio.clearSelection();
        for (Enumeration<AbstractButton> btns = btnGrpRadio.getElements(); btns.hasMoreElements();) {
             btnGrpRadio.remove(btns.nextElement());
        }
        return selectedVal;
   }
   
   private void showResult(){
       btnGrpRadio.clearSelection();
       for (Enumeration<AbstractButton> btns = btnGrpRadio.getElements(); btns.hasMoreElements();) {
            btnGrpRadio.remove(btns.nextElement());
       }
       panelAnswerArea.removeAll();
       lblResult.setText(result);
       panelAnswerArea.add(lblResult);
       panelAnswerArea.revalidate();
   }
   
   public void feedbackComplete(String newIdealEmployee) throws IOException, JessException{
        this.setEnabled(true);
        formFeedback.dispose();
        JOptionPane.showMessageDialog(this, newIdealEmployee);
        File file =new File("idealEmployeeConcept.clp");
        //if file doesnt exists, then create it
        if(!file.exists()){
            JOptionPane.showMessageDialog(this, "idealEmployeeConcept.clp file not found!!");
            return;
        }
        FileWriter fileWritter = new FileWriter(file.getName(),false);
        BufferedWriter bufferWritter = new BufferedWriter(fileWritter);
        bufferWritter.write(newIdealEmployee);
        bufferWritter.close();
        clipController.engine.clear();
        //reset the engine
        clipController = new ReteController();
        clipController.addListener(this);
        clipController.loadClipFile(clipFile);

        lblStatus.setText("New things learned!");
        jProgressBar1.setValue(jProgressBar1.getMinimum());
        jProgressBar1.setIndeterminate(false);
        btnSubmit.setEnabled(false);
        cmbInterviewType.setSelectedIndex(0);
        txtCandidateName.setText("");
        result = "Interview Reset";
        txtQuestion.setText("");
        ArrayList<Object> facts = clipController.GetAllFacts();
        for(int i= 0 ;i< facts.size();i++){
            System.out.println(facts.get(i).toString());
        }
        showResult();
   }
}
