/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vchro;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jess.JessException;

/**
 *
 * @author mamun028
 */
public class SupervisorFeedback extends javax.swing.JFrame {

    IdealEmployeeModel idealEmp;
    JFrame parent;
    /**
     * Creates new form SupervisorFeedback
     */
    public SupervisorFeedback(String employeeName, JFrame parent) throws Exception {
        initComponents();
        txtEmpName.setText(employeeName);
        idealEmp = new IdealEmployeeModel();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEmpName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ratingTrust = new javax.swing.JSlider();
        ratingNuro = new javax.swing.JSlider();
        ratingConsc = new javax.swing.JSlider();
        ratingExtro = new javax.swing.JSlider();
        ratingAgree = new javax.swing.JSlider();
        ratingCoach = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        ratingOverall = new javax.swing.JSlider();
        btnCancel = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Feedback for:");

        txtEmpName.setEditable(false);
        txtEmpName.setText("employee name");
        txtEmpName.setEnabled(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("We assume this employee worked for Armir for at least 6 month and your are post-evaluating him. This information will update Ideal Candidate model used for evaluating interviewee. In case the tenure is less than 6 month please click cancel.");
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("How would you rate Trustworthyness?");

        jLabel3.setText("How would you rate Neuroticism?");

        jLabel4.setText("How would you rate Conscientiousness?");

        jLabel5.setText("How would you rate Extrovertedness?");

        jLabel6.setText("How would you rate Agreeableness?");

        jLabel7.setText("How would you rate Coachability?");

        ratingTrust.setMajorTickSpacing(10);
        ratingTrust.setMaximum(50);
        ratingTrust.setMinorTickSpacing(1);
        ratingTrust.setPaintTicks(true);

        ratingNuro.setMajorTickSpacing(10);
        ratingNuro.setMaximum(50);
        ratingNuro.setMinorTickSpacing(1);
        ratingNuro.setPaintTicks(true);

        ratingConsc.setMajorTickSpacing(10);
        ratingConsc.setMaximum(50);
        ratingConsc.setMinorTickSpacing(1);
        ratingConsc.setPaintTicks(true);

        ratingExtro.setMajorTickSpacing(10);
        ratingExtro.setMaximum(50);
        ratingExtro.setMinorTickSpacing(1);
        ratingExtro.setPaintTicks(true);

        ratingAgree.setMajorTickSpacing(10);
        ratingAgree.setMaximum(50);
        ratingAgree.setMinorTickSpacing(1);
        ratingAgree.setPaintTicks(true);

        ratingCoach.setMajorTickSpacing(10);
        ratingCoach.setMaximum(50);
        ratingCoach.setMinorTickSpacing(1);
        ratingCoach.setPaintTicks(true);

        jLabel8.setText("How would you rate Overall?");

        ratingOverall.setMajorTickSpacing(10);
        ratingOverall.setMaximum(50);
        ratingOverall.setMinorTickSpacing(1);
        ratingOverall.setPaintTicks(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ratingTrust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratingNuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratingConsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratingExtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratingAgree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratingCoach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratingOverall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ratingTrust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ratingNuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(ratingConsc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(ratingExtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ratingAgree, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ratingCoach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ratingOverall, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(75, 75, 75))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, ratingTrust});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, ratingNuro});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, ratingConsc});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel5, ratingExtro});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel6, ratingAgree});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel7, ratingCoach});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel8, ratingOverall});

        btnCancel.setText("Cancel");

        btnSubmit.setText("Submit");
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmpName))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmit)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnCancel))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        Map<String,Double> feedbackInput = new HashMap<String,Double>(); //0~5
        feedbackInput.put("trust", ((double)ratingTrust.getValue())/10); //0~5
        double max = feedbackInput.get("trust");
        double min = feedbackInput.get("trust");
        String maxKey = "trust";
        String minKey = "trust";
        
        feedbackInput.put("neuro", ((double)ratingNuro.getValue())/10); //0~5
        if(max < feedbackInput.get("neuro")) {
            max = feedbackInput.get("neuro");
            maxKey = "neuro";
        }
        if(min > feedbackInput.get("neuro")) {
            min = feedbackInput.get("neuro");
            minKey = "neuro";
        }
        
        feedbackInput.put("consci", ((double)ratingConsc.getValue())/10); //0~5
        if(max < feedbackInput.get("consci")) {
            max = feedbackInput.get("consci");
            maxKey = "consci";
        }
        if(min > feedbackInput.get("consci")) {
            min = feedbackInput.get("consci");
            minKey = "consci";
        }
        
        feedbackInput.put("extro", ((double)ratingExtro.getValue())/10); //0~5
        if(max < feedbackInput.get("extro")) {
            max = feedbackInput.get("extro");
            maxKey = "extro";
        }
        if(min > feedbackInput.get("extro")) {
            min = feedbackInput.get("extro");
            minKey = "extro";
        }
        
        feedbackInput.put("agree", ((double)ratingAgree.getValue())/10); //0~5
        if(max < feedbackInput.get("agree")) {
            max = feedbackInput.get("agree");
            maxKey = "agree";
        }
        if(min > feedbackInput.get("agree")) {
            min = feedbackInput.get("agree");
            minKey = "agree";
        }
        
        feedbackInput.put("coach", ((double)ratingCoach.getValue())/10); //0~5
        if(max < feedbackInput.get("coach")) {
            max = feedbackInput.get("coach");
            maxKey = "coach";
        }
        if(min > feedbackInput.get("coach")){
            min = feedbackInput.get("coach");
            minKey = "coach";
        }
        
        feedbackInput.put("overall", ((double)ratingOverall.getValue())/5); //0~10
        
        if(feedbackInput.get("overall") >= 7){
            if(feedbackInput.get(minKey) <= 4.8 && feedbackInput.get(maxKey) >= 0.2){
                feedbackInput.put(minKey, feedbackInput.get(minKey) + 0.2);
                feedbackInput.put(maxKey, feedbackInput.get(maxKey) - 0.2);
            }
        }else if(feedbackInput.get("overall") <= 3){
            if(feedbackInput.get(maxKey) <= 4.8 && feedbackInput.get(minKey) >= 0.2){
                feedbackInput.put(maxKey, feedbackInput.get(maxKey) + 0.2);
                feedbackInput.put(minKey, feedbackInput.get(minKey) - 0.2);
            }
        }
        
        String prevIdeal = idealEmp.toString();
        idealEmp.setTrust(feedbackInput.get("trust"));
        idealEmp.setNeuro(feedbackInput.get("neuro"));
        idealEmp.setConsci(feedbackInput.get("consci"));
        idealEmp.setExtro(feedbackInput.get("extro"));
        idealEmp.setAgree(feedbackInput.get("agree"));
        idealEmp.setCoach(feedbackInput.get("coach"));
        
        String nowIdeal = idealEmp.toString();
        try {
            //JOptionPane.showMessageDialog(this,"Previous: "+prevIdeal+"\nUpdate: "+nowIdeal);
            ((MainGUI)parent).feedbackComplete(nowIdeal);
        } catch (IOException | JessException ex) {
            Logger.getLogger(SupervisorFeedback.class.getName()).log(Level.SEVERE, null, ex);
            this.dispose();
        }
        Logger.getLogger(SupervisorFeedback.class.getName()).log(Level.INFO,"Previous: "+prevIdeal+"\nUpdate: "+nowIdeal);
        
    }//GEN-LAST:event_btnSubmitMouseClicked

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SupervisorFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SupervisorFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SupervisorFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SupervisorFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new SupervisorFeedback("test",null).setVisible(true);
//                } catch (Exception ex) {
//                    Logger.getLogger(SupervisorFeedback.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JSlider ratingAgree;
    private javax.swing.JSlider ratingCoach;
    private javax.swing.JSlider ratingConsc;
    private javax.swing.JSlider ratingExtro;
    private javax.swing.JSlider ratingNuro;
    private javax.swing.JSlider ratingOverall;
    private javax.swing.JSlider ratingTrust;
    private javax.swing.JTextField txtEmpName;
    // End of variables declaration//GEN-END:variables
}
